
GET http://localhost:8080/api/v1/pizzas
#Authorization: Basic username password

###

POST http://localhost:8080/api/v1/pizzas/add
#Authorization: Basic username password
Content-Type: application/json

{
    "name": "Margheerita",
    "price": 11.0
}